export const theme = {
  backgroundColor: '#F5F7F5',
  cardBackground: '#FFFFFF',
  sectionBackground: '#EEF2EE',
  textColor: '#1A1A1A',
  textMuted: '#666666',
  timerColor: '#2E7D32',
  accentColor: '#2E7D32',
  checkboxActive: '#2E7D32',
  checkboxInactive: '#CCCCCC',
  strikeColor: '#AAAAAA',
  borderColor: '#E0E0E0',
  fontSize: {
    title: 24,
    exercise: 18,
    timer: 72,
    button: 16,
    small: 13,
    section: 14,
  },
} as const;
